pipeline {
    agent any

    options {
            skipDefaultCheckout(),
            timeout(time: 2 , unit: 'MINUTES')
        }
    stages {
        stage('Git Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/amberroutella/Devops_practice.git']] )
            }
        }

        stage('Build app') {
            steps {
                // Use a specific Maven installation if configured in Jenkins
                sh '''
                    cd my-spring-boot-app/
                    mvn clean install
                '''
            }
        }
        
        stage('Testing Jar') {
            steps {
                sh  '''
                cd my-spring-boot-app/
                java -jar target/*.jar test --server.port=8081
                '''
            }
        }
    }
}
