pipeline {
    agent any

    stages{
        stage('Checkout'){
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/amberroutella/Devops_practice.git']] )
            }
        }

        stage('Validating terraform'){
            steps {
                dir("${env.WORKSPACE}/devops_terraform/Terraform"){  
                    sh  'terraform init'
                    sh  'terraform validate'
                }
            }
        }    

        stage("Applying terraform"){
            steps{
                dir("${env.WORKSPACE}/devops_terraform/Terraform"){
                sh 'terraform apply -auto-approve'
                }
            }
        }    
        
        stage("Deploy to S3"){
            steps{
                dir("${env.WORKSPACE}/devops_terraform/"){
                sh 'aws s3 sync website/ s3://your-unique-bucket-name/'
                }
            }
        }            
    }
}